# Generated by Django 5.1.7 on 2025-03-28 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obituaries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obituary',
            name='content',
        ),
        migrations.RemoveField(
            model_name='obituary',
            name='submission_date',
        ),
        migrations.AddField(
            model_name='obituary',
            name='biography',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obituary',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='obituary',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
